import smtplib
import os
from email.mime.text import MimeText
from email.mime.multipart import MimeMultipart
from utils.logger import setup_logger

logger = setup_logger('email_alert')

class EmailAlert:
    def __init__(self):
        self.enabled = False
        self.smtp_server = os.getenv('SMTP_SERVER', '')
        self.smtp_port = int(os.getenv('SMTP_PORT', 587))
        self.smtp_username = os.getenv('SMTP_USERNAME', '')
        self.smtp_password = os.getenv('SMTP_PASSWORD', '')
        self.from_email = os.getenv('FROM_EMAIL', '')
        self.to_email = os.getenv('TO_EMAIL', '')
        
        if all([self.smtp_server, self.smtp_username, self.smtp_password]):
            self.enabled = True
            logger.info("Email alerts enabled")
        else:
            logger.warning("Email alerts disabled - missing configuration")
    
    def send_alert(self, alert_data):
        """Send email alert"""
        if not self.enabled:
            return False
            
        try:
            # Create message
            msg = MimeMultipart()
            msg['From'] = self.from_email
            msg['To'] = self.to_email
            msg['Subject'] = f"🚨 NIDS Alert: {alert_data['category']}"
            
            # Create email body
            body = f"""
            Network Intrusion Detection System Alert
            
            🔴 ALERT DETAILS:
            Category: {alert_data['category']}
            Message: {alert_data['message']}
            Source IP: {alert_data['src_ip']}
            Country: {alert_data['country']}
            Timestamp: {alert_data['timestamp']}
            
            📊 Additional Info:
            Severity: {alert_data.get('severity', 'medium')}
            
            This alert was generated by your NIDS system.
            """
            
            msg.attach(MimeText(body, 'plain'))
            
            # Send email
            server = smtplib.SMTP(self.smtp_server, self.smtp_port)
            server.starttls()
            server.login(self.smtp_username, self.smtp_password)
            server.send_message(msg)
            server.quit()
            
            logger.info(f"Email alert sent for {alert_data['category']}")
            return True
            
        except Exception as e:
            logger.error(f"Failed to send email alert: {e}")
            return False

# Global instance
email_alerter = EmailAlert()

def send_email_alert(alert_data):
    """Send email alert (wrapper function)"""
    return email_alerter.send_alert(alert_data)